config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :artists
  resources :directors
  resources :profiles
  resources :apps
  resources :movies
  resources :albums
  resources :websites

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/album.rb
class Album < ActiveRecord::Base
	validates :title, presence: true

	has_many :profiles
	has_many :users, through: :profiles
	belongs_to :artist
end

app/models/app.rb
class App < ActiveRecord::Base
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	has_many :profiles, through: :albums
	has_many :users, through: :profiles
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_many :movies
	has_many :profiles, through: :movies
	has_many :users, through: :profiles
end

app/models/movie.rb
class Movie < ActiveRecord::Base	
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
	belongs_to :director
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :app
	belongs_to :movie
	belongs_to :album
	belongs_to :website
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  has_one :profile

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  		where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  	else
  		where(conditions).first
  	end
  end
end

app/models/website.rb
class Website < ActiveRecord::Base
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :load_album, only: [:edit, :show, :update]

	def index
		@albums = Album.all
	end

  def show
  end

  def new
    @album = Album.new
    @artists = Artist.all.collect { |artist| [artist.name, artist.id] }
  end

  def create
    @album = Album.new(safe_album_params)
    if @album.save
      redirect_to @album
    else
      render 'new'
    end
  end

  private

  def load_album
  	@album = Album.find(params[:id])
  end

  def safe_album_params
    params.require('album').permit(:title, :artist_id)
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	before_action :load_app, only: :show

	def index
		@apps = App.all
	end

  def new
    @app = App.new
  end

  def show
  end

  def create
    @app = App.new(safe_app_params)
    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end

  private

  def load_app
  	@app = App.find(params[:id])
  end

  def safe_app_params
    params.require('app').permit(:name)
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  	@artists = Artist.all
  end

  def show
  	@artist = Artist.find(params[:id])
  end

  def new
  	@artist = Artist.new
  end

  def create
  	@artist.new(safe_artist_params)
  	if @artist.save
  		redirect_to @artist
  	else
  		render 'new'
  	end
  end

  private

  def safe_artist_params
  	params.require('artist').permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :load_movie, only: [:edit, :show, :update]

	def index
		@movies = Movie.all
	end

  def show
  end

  def new
    @movie = Movie.new
    @directors = Director.all.collect { |director| [director.name, director.id] }
  end

  def create
    @movie = Movie.new(safe_movie_params)
    if @movie.save
      redirect_to @movie
    else
      render 'new'
    end
  end

  private

  def load_movie
  	@movie = Movie.find(params[:id])
  end

  def safe_movie_params
    params.require('movie').permit(:name, :director_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<% if @album.errors.any? %>
	<h2>Oh noes, there were errors saving a new album!</h2>
	<ul>
		<% @album.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @album do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :artist %>
	<%= f.select :artist_id, @artists %>
	<br>
	<%= f.submit %>
<% end %>

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/index.html.erb
<h2>All Albums</h2>
<p><%= link_to "Add a New Album", new_album_path %></p>
<% if @albums.any? %>
	<ul>
	<% @albums.each do |album| %>
		<li><%= link_to "#{album.title}", album %> by <%= link_to "#{album.artist.name}", album.artist %></li>
	<% end %>
	</ul>
<% end %>

app/views/albums/new.html.erb
<h2>Add a New Album</h2>
<%= link_to "Add a New Artist", new_artist_path %>
<%= render 'form' %>

app/views/albums/show.html.erb
<h2><%= @album.title %> by <%= @album.artist.name %></h2>
<p>Everyone who likes this album:</p>
<ul>
<% @album.users.each do |user| %>
	<li><%= user.email %></li>
<% end %>
</ul>

app/views/artists/_form.html.erb
<% if @artist.errors.any? %>
	<h2>Oh noes, there were errors saving a new artist!</h2>
	<ul>
		<% @artist.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @artist do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h2>All Artists</h2>
<ul>
	<% @artists.each do |artist| %>
		<li><%= artist.name %></li>
	<% end %>
</ul>

app/views/artists/new.html.erb
<h2>Add a New Artist</h2>
<%= render 'form' %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<p>Albums by this Artist:</p>
<ul>
<% @artist.albums.each do |album| %>
	<li><%= link_to "#{album.title}", album %></li>
<% end %>
</ul>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>