config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :artists
  resources :directors
  resources :profiles
  resources :apps
  resources :movies
  resources :albums
  resources :websites

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/album.rb
class Album < ActiveRecord::Base
	validates :title, presence: true

	has_many :profiles
	has_many :users, through: :profiles
	belongs_to :artist
end

app/models/app.rb
class App < ActiveRecord::Base
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	has_many :profiles, through: :albums
	has_many :users, through: :profiles
end

app/models/director.rb
class Director < ActiveRecord::Base
	has_many :movies
	has_many :profiles, through: :movies
	has_many :users, through: :profiles
end

app/models/movie.rb
class Movie < ActiveRecord::Base	
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
	belongs_to :director
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :app
	belongs_to :movie
	belongs_to :album
	belongs_to :website
end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  has_one :profile

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  		where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  	else
  		where(conditions).first
  	end
  end
end

app/models/website.rb
class Website < ActiveRecord::Base
	validates :name, presence: true

	has_many :profiles
	has_many :users, through: :profiles
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
	before_action :load_app, only: :show

	def index
		@apps = App.all
	end

  def new
    @app = App.new
  end

  def show
  end

  def create
    @app = App.new(safe_app_params)
    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end

  private

  def load_app
  	@app = App.find(params[:id])
  end

  def safe_app_params
    params.require('app').permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/_form.html.erb
<% if @app.errors.any? %>
	<h2>Oh noes, there were errors saving a new app!</h2>
	<ul>
		<% @app.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @app do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/apps/create.html.erb
<h1>Apps#create</h1>
<p>Find me in app/views/apps/create.html.erb</p>

app/views/apps/index.html.erb
<h2>All Apps</h2>
<p><%= link_to "Add a New App", new_app_path %></p>
<% if @apps.any? %>
	<ul>
	<% @apps.each do |app| %>
		<li><%= link_to app.name, app %></li>
	<% end %>
	</ul>
<% end %>

app/views/apps/new.html.erb
<h2>Add a New App</h2>
<%= render 'form' %>

app/views/apps/show.html.erb
<h2><%= @app.name %></h2>
<p>All the folks who like this app:</p>
<ul>
<% @app.users.each do |user| %>
	<li><%= user.email %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desert Island Picks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1><%= link_to "Desert Island Picks", root_path %></h1>
	<%= link_to "Home", root_path %> |
	<%= link_to "Log out", destroy_user_session_path, :method => :delete %><br>
	<%= link_to "Movies", movies_path %> |
	<%= link_to "All Apps", apps_path %> |
	<%= link_to "All Albums", albums_path %> |
	<%= link_to "All Websites", websites_path %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>